"""Add EMI fields to Bill model

Revision ID: 0bc480a3d4ab
Revises: af22f22bc19c
Create Date: 2025-05-11 13:00:43.331260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bc480a3d4ab'
down_revision = 'af22f22bc19c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_emi', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('emi_months', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('emi_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('emi_start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('emi_interest_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('emi_total_amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.drop_column('emi_total_amount')
        batch_op.drop_column('emi_interest_rate')
        batch_op.drop_column('emi_start_date')
        batch_op.drop_column('emi_amount')
        batch_op.drop_column('emi_months')
        batch_op.drop_column('is_emi')

    # ### end Alembic commands ###
