"""add website to settings

Revision ID: 1ab2cd1ed97c
Revises: 0bc480a3d4ab
Create Date: 2025-05-11 14:38:57.103396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ab2cd1ed97c'
down_revision = '0bc480a3d4ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.drop_column('emi_months')
        batch_op.drop_column('emi_total_amount')
        batch_op.drop_column('emi_interest_rate')
        batch_op.drop_column('is_emi')
        batch_op.drop_column('emi_start_date')
        batch_op.drop_column('emi_amount')

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('website')

    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emi_amount', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('emi_start_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('is_emi', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('emi_interest_rate', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('emi_total_amount', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('emi_months', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
