"""Add discount and paid_amount to Bill model

Revision ID: 2315d397d772
Revises: 
Create Date: 2025-05-15 20:52:49.011612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2315d397d772'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill', sa.Column('discount', sa.Float(), nullable=True))
    op.add_column('bill', sa.Column('paid_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bill', 'paid_amount')
    op.drop_column('bill', 'discount')
    # ### end Alembic commands ###
