"""Replace warranty with hsn_sac_number

Revision ID: 44e639ee39dd
Revises: 
Create Date: 2025-05-11 21:58:04.717532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44e639ee39dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hsn_sac_number', sa.String(length=20), nullable=True))
        batch_op.drop_column('warranty')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warranty', sa.INTEGER(), nullable=True))
        batch_op.drop_column('hsn_sac_number')

    # ### end Alembic commands ###
