"""Add bank account number and IFSC code to settings

Revision ID: 49c9f7a0bbfd
Revises: 44e639ee39dd
Create Date: 2025-05-11 22:09:58.701076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49c9f7a0bbfd'
down_revision = '44e639ee39dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_account_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ifsc_code', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('ifsc_code')
        batch_op.drop_column('bank_account_number')

    # ### end Alembic commands ###
