"""Add inventory_updated field to Bill model

Revision ID: af22f22bc19c
Revises: f8609c3cc27a
Create Date: 2025-05-11 11:34:57.871080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af22f22bc19c'
down_revision = 'f8609c3cc27a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inventory_updated', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.drop_column('inventory_updated')

    # ### end Alembic commands ###
